# Generated by Django 4.1 on 2022-09-25 15:06

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topping',
            name='urlsImage',
            field=models.ImageField(default='', upload_to=api.models.upload_to),
        ),
    ]
