# Generated by Django 4.1 on 2022-09-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_topping_urlsimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topping',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
