# Generated by Django 4.1 on 2022-08-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_topping_coffee_volume_coffee_available_toppings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='price',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='volume',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='topping',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='topping',
            name='price',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='topping',
            name='volume',
            field=models.IntegerField(null=True),
        ),
    ]
