# Generated by Django 4.1 on 2022-09-25 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_topping_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dessert',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.dessert'),
        ),
        migrations.AlterField(
            model_name='order',
            name='topping',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.topping'),
        ),
    ]
