# Generated by Django 4.2 on 2023-04-09 13:06

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_order_coffee_remove_order_dessert_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('type', models.TextField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('volume', models.IntegerField(null=True)),
                ('urlsImage', models.ImageField(upload_to=api.models.upload_to)),
                ('urlsIcon', models.ImageField(upload_to=api.models.upload_to)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
