# Generated by Django 4.2 on 2023-04-10 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_order_coffee_remove_order_dessert_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='coffee',
            field=models.ManyToManyField(to='api.coffee'),
        ),
        migrations.AddField(
            model_name='order',
            name='dessert',
            field=models.ManyToManyField(to='api.dessert'),
        ),
        migrations.AddField(
            model_name='order',
            name='topping',
            field=models.ManyToManyField(to='api.topping'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_cost',
            field=models.IntegerField(default=0),
        ),
    ]
