# Generated by Django 4.1 on 2023-05-05 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_order_coffee_remove_order_dessert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
